* Installing i3 window manager
  Every system has a window manager. i3 is a tiling window manager. It does not have
  any maximize button or so. On a clean Ubuntu installation:
  #+BEGIN_SRC sh
    sudo apt-get install i3
  #+END_SRC
  
  While installing don't forget to generate a config file when prompted. This will also install
  some key bindings. Use windows key for mode key (recommended)
* Config file
- Config file is: ~/.config/i3/config
* Built-in key-bindings
- Mode-Enter : Terminal window
- Mode-Shift-q : Quit window
- Mode-d : dmenu app
- Mode-v : vertical mode for the next opened window
- Mode-Arrow keys : move between windows
- Mode-r : resize mode (ESC to escape resive mode), use arrow keys to make wider or narrower
- Mode-Shift-Arrow keys : shift windows in between
- Mode-0,1,2.. : navigate in workspaces
- Mode-Shift- 0,1,2.. : move current window to the workspace
- Mode-Shift-e : log out
* Using some apps with i3
** feh for wallpapers
use this program to install wallpapers on i3
   #+BEGIN_SRC sh
     sudo apt install feh   
   #+END_SRC
** Font Awesome (for icons)
- Download Font Awesome from https://github.com/FortAwesome/Font-Awesome/releases.
- Unzip it and copy it to the ~/.fonts/ folder
** Fonts
- Downloaded fonts must be copied into either your system font folder (often /usr/share/fonts/) or user font folder (often ~/.local/share/fonts/ or /usr/local/share/fonts)
- users .fonts/ folder will not be used in the future (
- fonts can be recached like:
#+BEGIN_SRC sh
  fc-cache -fv
#+END_SRC
- fonts that are loaded can be found by:
#+BEGIN_SRC sh
  fc-list | grep "Awesome"
#+END_SRC
** Font for i3 windows  
- Download San Francisco font from https://github.com/supermarin/YosemiteSanFranciscoFont
- Unzip it and copy it to the ~/.fonts/ folder
 
