* Installing i3 window manager
  Every system has a window manager. i3 is a tiling window manager. It does not have
  any maximize button or so. On a clean Ubuntu installation:
  #+BEGIN_SRC sh
    sudo apt-get install i3
  #+END_SRC
  
  While installing don't forget to generate a config file when prompted. This will also install
  some key bindings. Use windows key for mode key (recommended)
* Config file
- Config file is: ~/.config/i3/config
* Built-in key-bindings
- Mode-Enter : Terminal window
- Mode-Shift-q : Quit window
- Mode-d : dmenu app
- Mode-v : vertical mode for the next opened window
- Mode-Arrow keys : move between windows
- Mode-r : resize mode (ESC to escape resive mode), use arrow keys to make wider or narrower
- Mode-Shift-Arrow keys : shift windows in between
- Mode-0,1,2.. : navigate in workspaces
- Mode-Shift- 0,1,2.. : move current window to the workspace
- Mode-Shift-e : log out
* Using some apps with i3
** feh for wallpapers
use this program to install wallpapers on i3
   #+BEGIN_SRC sh
     sudo apt install feh   
   #+END_SRC
** Font Awesome (for icons)
- Download Font Awesome from https://github.com/FortAwesome/Font-Awesome/releases.
- Unzip it and copy it to the ~/.fonts/ folder
** Fonts
- Downloaded fonts must be copied into either your system font folder (often /usr/share/fonts/) or user font folder (often ~/.local/share/fonts/ or /usr/local/share/fonts)
- users .fonts/ folder will not be used in the future (
- fonts can be recached like:
#+BEGIN_SRC sh
  fc-cache -fv
#+END_SRC
- fonts that are loaded can be found by:
#+BEGIN_SRC sh
  fc-list | grep "Awesome"
#+END_SRC
** Font for i3 windows  
- Download San Francisco font from https://github.com/supermarin/YosemiteSanFranciscoFont
- Unzip it and copy it to the ~/.fonts/ folder
* GTK Themes and Fonts
- Download lxappearance from apt
- Once you open lxappearance, change something, and a file called .gtkrc-2.0 is created in home
- Change the font in .gtkrc-2.0 to System San Francisco Display
#+BEGIN_SRC sh
  gtk-font-name="System San Francisco Display 10"  
#+END_SRC 
- You may also change the gtk theme from lxappearence
** Arc theme
- https://github.com/horst3180/arc-theme
- from above link follow instructions
- get libgtk-3-dev with apt install
* Using scripts with i3
- You need to download scripts to below folders before you copy configure file of i3 from git
- First, mkdir ~/.i3 and ~/.i3/scripts 
- Put scripts in there
- Scripts must be executable (chmod to 755)
* Using rofi 
- Rofi setting are in the .Xresources file
* Setting Caps Lock and Escape 
- These settings are done in the .config/i3/config file
#+BEGIN_SRC sh
  exec_always xmodmap -e "clear lock" #disable caps lock switch
  exec_always xmodmap -e "keysym Caps_Lock = Escape" #set caps_lock as escape
#+END_SRC
* Installing i3-gaps
-  check out for instructions: https://gist.github.com/boreycutts/6417980039760d9d9dac0dd2148d4783

** Installing i3-gaps

*** Dependencies
i3-gaps has some packages that are required for it to work so install these things:
#+BEGIN_SRC sh
sudo apt install libxcb1-dev libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev libxcb-icccm4-dev libyajl-dev libstartup-notification0-dev libxcb-randr0-dev libev-dev libxcb-cursor-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev autoconf xutils-dev libtool 
#+END_SRC

You also need to install `libxcb-xrm-dev`, but I got `Unable to locate package libxcb-xrm-dev` when trying to install from the apt repositories on Ubuntu 16.04. If this happens to you, just install it from source using these commands:
#+BEGIN_SRC sh
mkdir tmp
cd /tmp
git clone https://github.com/Airblader/xcb-util-xrm
cd xcb-util-xrm
git submodule update --init
./autogen.sh --prefix=/usr
make
sudo make install
#+END_SRC

*** Installing
gaps also needs to be installed from source so run these commands:
#+BEGIN_SRC sh
  cd /tmp
  git clone https://www.github.com/Airblader/i3 i3-gaps
  cd i3-gaps
  git checkout gaps && git pull //if you do this it will go to gaps branch instead of next branch. next / gaps-next are the development branches. You have next-gaps in your home pc
  autoreconf --force --install
  rm -rf build
  mkdir build
  cd build
  ../configure --prefix=/usr --sysconfdir=/etc
  make
  sudo make install
#+END_SRC
Now i3-gaps should be installed.

*** Configuring
To enable gaps you need to set some variables in your i3 config.
#+BEGIN_SRC sh 
gaps inner <# of pixels>
gaps outer <# of pixels>
#+END_SRC

Add this to get rid of titlebars because gaps doen't work with titlebars:
#+BEGIN_SRC sh
for_window [class="^.*"] border pixel 2
#+END_SRC

Refresh i3 and you're good to go!
* Installing i3blocks-gaps
- check https://github.com/Airblader/
- you may use /tmp folder for the git clone commmand
- this This repository is a fork of i3blocks made to be compatible with i3-gaps, itself a fork of i3wm.
- copy i3blocks config file into ~/.config/i3blocks/ 
- scripts come with the repository. Copy them to the ~/.i3/i3blocks-scripts ($ cp /tmp/i3blocks/scripts/* ~/.i3/i3blocks-script)
- use ~/.i3/i3blocks-scripts as SCRIPT_DIR in i3 config file bar section:
#+BEGIN_SRC sh
  bar {
  status_command SCRIPT_DIR=/home/orcan/.i3/i3blocks-scripts i3blocks
  }
#+END_SRC
* Installing Ranger
- Install it from apt: sudo apt install ranger
- Then copy the config file: ranger --copy-config=all
