#!/bin/bash
while [ "$select" = ""  ]; do
    select=$(echo -e 'BACK\nSUSPEND\nPOWER OFF\nLOG-OUT' | dmenu -nb '#2f343f' -nf '#f3f4f5' -sb '#9575cd' -sf '#f3f4f5' -fn '-*-*-medium-r-normal-*-*-*-*-*-*-100-*-*' -i -p "How do you wanna exit?")
    [ -z "$select" ] && exit 0
done
[ "$select" = "BACK" ] && exit 0
[ "$select" = "LOG-OUT" ] && i3-msg exit
[ "$select" = "SUSPEND" ] && systemctl suspend
[ "$select" = "POWER OFF" ] && systemctl poweroff
