#!/bin/bash

# Thsi script changes all the specified word with the other in all files in folders recursively

i=1
for file in $(find ~/test/ -name '*.tex')
do
	echo "$i : $file"
	i=$((i+1))
	sed -i "s/${1}/${2}/g" "$file"
done
