#!/bin/bash

# This script recursively removes txt files

#find $(pwd) -type f -name "*.txt" -print0 | xargs -0 rm -f

i=1
for file in $(find $(pwd) -type f -name '*.tex~')
do
	#base=${file%.*}
	#ext=${file##*.}
	#basefile=$(basename "$file" "$ext")
	echo "orcan $i : $file"
	rm $file
	i=$((i+1))
done
