#!/bin/bash

# This scripts searchs pdfs for doi number. If finds 
# grep -o 'doi:.*' ndt.tex | sed -e 's/\.$//' -e 's/doi://'  
# -o option greps only the matching parts of the line, sed part removes doi: and the period at the end

i=1
for file in *.pdf
do
	if pdftotext $file - | grep -i -q "doi"; then
	echo "$i : $file" 
	i=$((i+1))
	DOI="$( pdftotext $file - | grep -io 'doi.*' | sed -e 's/\.$//' -e 's/doi://' )"
	doi2bib	$DOI
	fi
done
