#!/bin/bash

# Volume control with amixer

newvol="pkill -RTMIN+10 i3blocks"

[ -z "$2" ] && num="5%" || num="$2%"

case "$1" in 
	u) amixer -q -D pulse sset Master "$num"+ unmute ; $newvol ;;	
	d) amixer -q -D pulse sset Master "$num"- unmute ; $newvol ;;
	s) amixer -q -D pulse sset Master "$num" ; $newvol ;;
	m) amixer -q -D pulse sset Master toggle ; $newvol ;;
esac
