#+TITLE: Linux Audio Production Setup
* Low latency kernel
  - Install with apt:
    #+BEGIN_SRC sh
      sudo apt install linux-lowlatency
    #+END_SRC
  - If this does not work, try running it again after installing KXStudio repositories.
* Add user to audio group 
  - sudo usermod -a -G audio [USERNAME]
* KXStudio Repository Installation
  - KXStudio Repositories: http://kxstudio.linuxaudio.org/Repositories 
  - For Debian/Ubuntu:
    #+BEGIN_SRC sh
      # Install required dependencies if needed
      sudo apt-get install apt-transport-https software-properties-common wget

      # Download package file
      wget https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos_9.5.1~kxstudio3_all.deb

      # Install it
      sudo dpkg -i kxstudio-repos_9.5.1~kxstudio3_all.deb    
    #+END_SRC
  - If you're using a system newer or equal to Debian 9 (Stretch) or Ubuntu 16.04 (Xenial) you'll also need to enable GCC5 packages.
    #+BEGIN_SRC sh
      # Install required dependencies if needed
      sudo apt-get install libglibmm-2.4-1v5

      # Download package file
      wget https://launchpad.net/~kxstudio-debian/+archive/kxstudio/+files/kxstudio-repos-gcc5_9.5.1~kxstudio3_all.deb

      # Install it
      sudo dpkg -i kxstudio-repos-gcc5_9.5.1~kxstudio3_all.deb    
    #+END_SRC
  - Update the repos:
    #+BEGIN_SRC sh
      sudo apt update   
    #+END_SRC
* Install KXStudio Packages
  - Two packages to be installed:
    #+BEGIN_SRC sh
      sudo apt install kxstudio-default-settings
      sudo apt install kxstudio-meta-all 
    #+END_SRC
  - During installation a package confirmation screen appears. Hit the TAB to confirm installation.
* Install the PulseAudio Jack Module
  - Connection from pulseaudio to jack
    #+BEGIN_SRC sh
      sudo apt install pulseaudio-module-jack
    #+END_SRC
* JACK Settings with Cadence
  - See sound-notes on github/orcankolan
  - Jack Bridges->ALSA Audio : ALSA -> Loop -> JACK
  - Jack Bridges -> PulseAudio : Start
  - Use PulseAudio Bridge for JACK and enable auto-start at login
  - Configure -> Engine -> Realtime : Enabled
  - Configure -> Engine -> Realtime -> Priority : 10
  - Configure -> Engine -> Realtime -> Client timeout : 0
  - Configure -> Engine -> Realtime -> Port Max : 2048
  - Configure -> Engine -> Clock Source : System
  - Configure -> Engine -> Self Connect Mode : Don't restrict self connect requests
  - Configure -> Driver -> ALSA
  - Configure -> Driver -> ALSA -> Output, Input Device : USB Audio
  - Configure -> Driver -> ALSA -> Input, Output Channels : 6
  - Configure -> Driver -> ALSA -> Sample Rate : 44100
  - Configure -> Driver -> ALSA -> Buffer : 256 (see sound-notes)
  - Configure -> Driver -> ALSA -> Periods : 3 (see sound-notes)
* Visit Youtube - LinuxStudio Channel 

