* What is JACK and PulseAudio?
  Both are sound servers running above ALSA. 
  Many Linux systems now use PulseAudio as the default sound server, using it to handle all sound playback (media players, desktop alerts, web browsers and more). but while PulseAudio is running, JACK cannot access the same soundcard that Pulse is using.
** Jack is a sound server
   JACK is focused on the needs of pro-audio and music creation users. It offers the lowest possible latency, complete routing flexibility between applications and audio hardware, and all audio is always sample synchronized - apps don’t run ahead or behind of others. It doesn’t provide the smooth desktop experience that PulseAudio is aiming at.
** PulseAudio is a sound server
   PulseAudio is focused on desktop and mobile audio needs. It doesn’t try to address low latency usage, but does provide seamless device switching, network routing, global per-application volume control and lots more great stuff.
** Combining PulseAudio and JACK   
   Route PulseAudio to JACK while JACK is running. This can be easily done by installing Cadence
** Connections
   - This is JACK's strong point. Any inputs and outputs from your audio interface and/or JACK aware programs can arbitrarily be connected together.
   - JACK not only deals with connections between programs but also within programs. Any JACK aware program uses JACK to manage its inputs and outputs. This is what Ardour does.
** JACK Managers / JACK Connection Managers
*** Cadence (JACK Manager)
   This is an easy to use tool for setting up and starting JACK. It comes as part of the KXStudio distro and includes JACK bridges, which allow you to play normal desktop sounds, such as flash video, through JACK. Cadence can also start JACK on login, including JACK bridges. If you set it up once, there is very little maintenance thereafter.
*** Catia (JACK Connection Manager)
    Catia is a visual connection manager for JACK. It uses canvas. It can be accessed from Cadence
* JACK Settings
** Buffer size, sometimes called frames/period
   In a nutshell - Smaller buffer sizes produce less monitoring latency. 

   More in-depth details - A lower setting will make the computer work faster, which will allow for lower latency, but at the expense of increased CPU usage. Higher (larger) settings are more stable but you won't get low monitoring latency with them. If you are looking to achieve low latency monitoring, a setting between 64 – 256 will give you usable results.
** Sample Rate
   In a nutshell - Higher sample rates result in less latency, for the same buffer setting.

   More in-depth details – This settings is dependent on the optimal settings for your audio interface and your own personal preference. Some people prefer to record at higher sample rates, others are happy with 44100 (44.1kHz), which is CD quality. Another common setting is 48000, which some interfaces work better at. The higher you go with this setting, the lower your latency will be but you will push your CPU harder, which may result in xruns (pops and clicks).
** Periods/buffer
  In a nutshell – If you are using a USB device, you may achieve more stable low latency by setting this to 3. Otherwise, use a setting of 2.

  If you wish to achieve low latency settings, it can be a balancing act to find out what works best without pushing your CPU too hard. If you don't need to monitor your audio through your computer with low latency, there is no need to push your computer any more than it needs. You are better off staying with a higher setting and keeping reliability a high priority. If you have the option of hardware monitoring from your interface, use this to monitor your recordings instead. 
* After Settings
  Once you have these settings set up, you can then use any JACK aware programs and they will run with those settings. Some programs will allow you to change your buffer size, so that you can adjust audio latency without having to restart JACK.
* Useful links
- https://libremusicproduction.com/articles/demystifying-jack-%E2%80%93-beginners-guide-getting-started-jack
* JACK sync
 Another aspect of JACK that can be useful is JACK sync. Not only can you interconnect programs, you can also make sure that their transports run in sync. 
 - By default, Ardour is set to be JACK timemaster, which is what we want. This setting can be found by navigating to session > properties and going to the timecode tab. We will leave this enabled for now though.
* Using ffmpeg, JACK and PulseAudio
- To record from the terminal with ffmpeg program:
    #+BEGIN_SRC sh
      ffmpeg -f alsa -ac 1 -i default out1.wav 
    #+END_SRC
- -f -> for alsa device
- -ac -> for audio channel 1 (mono), Usually the default value is "1" (mono) for Mic input and "2" (stereo) for Line-In input
- -i -> for input (may be arbitrary number of input "files" (which can be regular files, pipes, network streams, grabbing devices, etc.),
- default device is the device that you set in the Cadence. Also with the jack connections set by Catia.
