#!/bin/bash

#generate array of begin line numbers:

#two dimensional arrays (first dimension is file, second is position)
declare -Ag begin_arrays
declare -Ag end_arrays

#echo ${begin_arrays[1,2]}

#file size in current directory:
file_num=$(find . -type f -name 'u_*.tex' | wc -l)

echo "First index length: $((file_num-1))"

list_begins () {
	echo "Listing Begin Positions:"
	i=1
	for file in $(find . -type f -name 'u_*.tex' | sort)
	do
		declare -g "begin_array_$i=( $(grep -n 'begin.question' $file | cut -d: -f 1) )"
		var="begin_array_$i"
		t=${!var}
		echo $t	
		i=$((i+1))
	done
}

list_ends () {
	echo "Listing End Positions:"
	i=1
	for file in $(find . -type f -name 'u_*.tex' | sort)
	do
		declare -g "end_array_$i=( $(grep -n 'end.question' $file | cut -d: -f 1) )"
		var="end_array_$i"
		t=${!var}
		echo $t	
		i=$((i+1))
	done
}

create_begins () {
	i=0
	for file in $(find . -type f -name 'u_*.tex' | sort)
	do
		j=0
		for value in $(grep -n 'begin.question' $file | cut -d: -f 1)
		do	
			begin_arrays[$i,$j]=$value
			j=$((j+1))
		done

		i=$((i+1))
	done
	}

create_ends () {
	i=0
	for file in $(find . -type f -name 'u_*.tex' | sort)
	do
		j=0
		for value in $(grep -n 'end.question' $file | cut -d: -f 1)
		do	
			end_arrays[$i,$j]=$value
			j=$((j+1))
		done

		i=$((i+1))
	done
	}

list_begins

list_ends

create_begins

echo ${begin_arrays[7,2]} 


n=$( qsize u_9_donanim_kontrol.tex | cut -d: -f 2)
echo "size of donanim:$((n))"
temp_array=( $(for ((i=0;i<$((n));i+=1)); do echo ${i}; done) )
shuff_array=( $(shuf -e "${temp_array[@]}") )
echo ${shuff_array[*]}

total_questions=${#begin_arrays[@]}	
echo "total number of general questions:$total_questions"

nq=$( echo "print int(round(float($n)*40/$total_questions))" | python )
echo "Needed questions (weighed) for 40 General Qs: $nq"

#sed -n "14,25p" all-questions.tex >> rand-question.tex











