#!/bin/bash

# To remove standart names present in the specific questions

if [ ! -f "./specific-questions.tex" ]; then
	echo "No file called specific-questions. Exiting!"
else
	echo "specific-questions file is found and removing subtitles..."

	sed -i -r 's/subtitle=\s?[a-zA-Z]*\s?\w*\s?\w*-?\w*/subtitle=/' specific-questions.tex 
fi


