#!/bin/bash

#questions_loc=~/supplement/test-questions/quesbook/questions
questions_loc=~/test-questions/quesbook/questions

g_chapter_array=(1 2 4 5 6 7 8 9)

unify_general() {

if [ ! -d "./unified" ]; then
	mkdir ./unified
else
	rm -rf ./unified
	mkdir ./unified
fi

for index in ${!g_chapter_array[*]}
do
	f_array=(`find . -type f -regextype egrep -regex ".*/o?n?_?(${g_chapter_array[index]}).*\.tex$" | sort`)

	if [[ -n ${f_array[*]} ]]; then #if file array is not empty
		echo "Unifying below files and moving them into unified directory..."
		printf "%4d: %s ; %s\n" $index ${f_array[0]} ${f_array[1]} 

		base=${f_array[0]%.*}
		filebase=$(basename "$base" ".tex")
		uni_name=./unified/u_${filebase}.tex

		cat ${f_array[0]}>$uni_name
		echo >> $uni_name
		cat ${f_array[1]}>>$uni_name
	else
		echo "General Question unification is not done..."
		break
	fi
done
}

s_chapter_array=(3)

unify_specific() {

if [ ! -d "./unified" ]; then
	mkdir ./unified
else
	rm -rf ./unified
	mkdir ./unified
fi

for index in ${!s_chapter_array[*]}
do
	f_array=(`find . -type f -regextype egrep -regex ".*/o?n?_?(${s_chapter_array[index]}).*\.tex$" | sort`)

	if [[ -n ${f_array[*]} ]]; then #if file array is not empty
		echo "Unifying below files and moving them into unified directory..."
		printf "%4d: %s ; %s\n" $index ${f_array[0]} ${f_array[1]} 

		base=${f_array[0]%.*}
		filebase=$(basename "$base" ".tex")
		uni_name=./unified/u_${filebase}.tex

		cat ${f_array[0]}>$uni_name
		echo >> $uni_name
		cat ${f_array[1]}>>$uni_name
	else
		echo "Specific Question unification is not done..."
		break
	fi
done

gather_specific

}

gather_specific () {
	echo "Gathering other below specific files into unified directory:"
	for file in $(find $(pwd) -type f -name 'p*.tex' | sort)
	do
		echo $file

		base=${file%.*}
		filebase=$(basename "$base" ".tex")
		uni_name=./unified/u_${filebase}.tex

		cp $file $uni_name
	done

}

cd ..

echo "Going to General Directory..."
cd $questions_loc/general
unify_general

echo "Going to Specific Directory..."
cd $questions_loc/specific
unify_specific


